language: java

branches:
  only:
    - master
    - /^release(-|_).*$/
    - /^dev(-|_).*$/
    - /^v(\d+.){1,2}\d+.*$/

services:
  - docker


jdk:
#  - oraclejdk8
  - openjdk8

cache:
  npm: true
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.sonar
addons:
  sonarcloud:
    organization: "aurorasic-github"

before_install:
  #  - npm i -g npm
  #  - npm i -g yarn
  - yarn global add @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint

install: mvn clean install -DskipTests=true -Ddockerfile.skip -Dmaven.javadoc.skip=true -B -V

script: skip

after_success:
  - mvn jacoco:report  sonar:sonar
  - bin/deploy-snapshot.sh
